package com.spaceline.client.module.world;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Horses. A toggleable world feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class HorsesModule extends ToggleModule {

    public HorsesModule() {
        super("horses", "Horses", ModuleCategory.WORLD, "Horses");    }
}
