package com.spaceline.client.module.world;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Time Changer. A toggleable world feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class TimeChangerModule extends ToggleModule {

    public TimeChangerModule() {
        super("time_changer", "Time Changer", ModuleCategory.WORLD, "Time Changer");
        register(new NumberSetting("time", "Time", "Client-side world time", 6000, 0, 24000, 100));
    }
}
