package com.spaceline.client.module.world;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Waypoints. A toggleable world feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class WaypointsModule extends ToggleModule {

    public WaypointsModule() {
        super("waypoints", "Waypoints", ModuleCategory.WORLD, "Waypoints");    }
}
