package com.spaceline.client.module.performance;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Cull Logs. A toggleable performance feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class CullLogsModule extends ToggleModule {

    public CullLogsModule() {
        super("cull_logs", "Cull Logs", ModuleCategory.PERFORMANCE, "Cull Logs");    }
}
