package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Autohide HUD. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class AutohideHudModule extends ToggleModule {

    public AutohideHudModule() {
        super("autohide_hud", "Autohide HUD", ModuleCategory.UTILITY, "Autohide HUD");    }
}
