package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Backups. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class BackupsModule extends ToggleModule {

    public BackupsModule() {
        super("backups", "Backups", ModuleCategory.UTILITY, "Backups");
        register(new NumberSetting("interval", "Interval (min)", "Auto-backup interval", 10, 1, 120, 1));
    }
}
