package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Inventory. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class InventoryModule extends ToggleModule {

    public InventoryModule() {
        super("inventory", "Inventory", ModuleCategory.UTILITY, "Inventory");    }
}
