package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.BooleanSetting;

/**
 * Screenshot Tools. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class ScreenshotToolsModule extends ToggleModule {

    public ScreenshotToolsModule() {
        super("screenshot_tools", "Screenshot Tools", ModuleCategory.UTILITY, "Screenshot Tools");
        register(new BooleanSetting("copy_clipboard", "Copy to clipboard", "Copy screenshots automatically", true));
    }
}
