package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Snaplook. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class SnaplookModule extends ToggleModule {

    public SnaplookModule() {
        super("snaplook", "Snaplook", ModuleCategory.UTILITY, "Snaplook");    }
}
