package com.spaceline.client.module.utility;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * UI Scaling. A toggleable utility feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class UiScalingModule extends ToggleModule {

    public UiScalingModule() {
        super("ui_scaling", "UI Scaling", ModuleCategory.UTILITY, "UI Scaling");
        register(new NumberSetting("scale", "GUI scale", "Custom GUI scale", 1.0, 0.5, 4.0, 0.25));
    }
}
