package com.spaceline.client.module.movement;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Jump Reset. A toggleable movement feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class JumpResetModule extends ToggleModule {

    public JumpResetModule() {
        super("jump_reset", "Jump Reset", ModuleCategory.MOVEMENT, "Jump Reset");    }
}
