package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Color Saturation. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class ColorSaturationModule extends ToggleModule {

    public ColorSaturationModule() {
        super("color_saturation", "Color Saturation", ModuleCategory.VISUAL, "Color Saturation");
        register(new NumberSetting("saturation", "Saturation", "World colour saturation", 1.0, 0.0, 3.0, 0.05));
    }
}
