package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Custom Fog. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class CustomFogModule extends ToggleModule {

    public CustomFogModule() {
        super("custom_fog", "Custom Fog", ModuleCategory.VISUAL, "Custom Fog");
        register(new NumberSetting("density", "Density", "Fog density", 1.0, 0.0, 2.0, 0.05));
    }
}
