package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Mob Overlay. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class MobOverlayModule extends ToggleModule {

    public MobOverlayModule() {
        super("mob_overlay", "Mob Overlay", ModuleCategory.VISUAL, "Mob Overlay");    }
}
