package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Motion Blur. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class MotionBlurModule extends ToggleModule {

    public MotionBlurModule() {
        super("motion_blur", "Motion Blur", ModuleCategory.VISUAL, "Motion Blur");
        register(new NumberSetting("strength", "Strength", "Blur amount", 0.5, 0.0, 1.0, 0.05));
    }
}
