package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Nametags. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class NametagsModule extends ToggleModule {

    public NametagsModule() {
        super("nametags", "Nametags", ModuleCategory.VISUAL, "Nametags");
        register(new NumberSetting("scale", "Scale", "Nametag scale", 1.0, 0.5, 3.0, 0.1));
    }
}
