package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Player Model. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class PlayerModelModule extends ToggleModule {

    public PlayerModelModule() {
        super("player_model", "Player Model", ModuleCategory.VISUAL, "Player Model");    }
}
