package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Subtitles. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class SubtitlesModule extends ToggleModule {

    public SubtitlesModule() {
        super("subtitles", "Subtitles", ModuleCategory.VISUAL, "Subtitles");    }
}
