package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Title Tweaker. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class TitleTweakerModule extends ToggleModule {

    public TitleTweakerModule() {
        super("title_tweaker", "Title Tweaker", ModuleCategory.VISUAL, "Title Tweaker");    }
}
