package com.spaceline.client.module.visual;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * View Model. A toggleable visual feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class ViewModelModule extends ToggleModule {

    public ViewModelModule() {
        super("view_model", "View Model", ModuleCategory.VISUAL, "View Model");    }
}
