package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Boss Bar HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class BossBarModule extends HudModule {

    public BossBarModule() {
        super("boss_bar", "Boss Bar", "Boss Bar overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        if (!game.inGame()) {
            return List.of();
        }
        return List.of("Boss Bar");
    }
}
