package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;
import com.spaceline.common.module.setting.NumberSetting;

/**
 * Custom Crosshair HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class CustomCrosshairModule extends HudModule {

    public CustomCrosshairModule() {
        super("custom_crosshair", "Custom Crosshair", "Custom Crosshair overlay");
        register(new NumberSetting("size", "Size", "Crosshair size", 4, 1, 16, 1));
    }

    @Override
    protected List<String> lines(GameState game) {
        if (!game.inGame()) {
            return List.of();
        }
        return List.of("Custom Crosshair");
    }
}
