package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;
import com.spaceline.common.module.setting.BooleanSetting;

/**
 * Keystrokes HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class KeystrokesModule extends HudModule {

    public KeystrokesModule() {
        super("keystrokes", "Keystrokes", "Keystrokes overlay");
        register(new BooleanSetting("mouse_buttons", "Mouse buttons", "Show LMB/RMB keys", true));
    }

    @Override
    protected List<String> lines(GameState game) {
        if (!game.inGame()) {
            return List.of();
        }
        return List.of("Keystrokes");
    }
}
