package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Playtime HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class PlaytimeModule extends HudModule {

    public PlaytimeModule() {
        super("playtime", "Playtime", "Playtime overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        return List.of("Playtime: " + formatSession());
    }

    private final long sessionStart = System.currentTimeMillis();

    private String formatSession() {
        long seconds = (System.currentTimeMillis() - sessionStart) / 1000;
        return String.format("%d:%02d:%02d", seconds / 3600, (seconds % 3600) / 60, seconds % 60);
    }
}
