package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Saturation HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class SaturationModule extends HudModule {

    public SaturationModule() {
        super("saturation", "Saturation", "Saturation overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        return List.of(String.format("Saturation: %.1f", game.saturation()));
    }
}
