package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Scoreboard HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class ScoreboardModule extends HudModule {

    public ScoreboardModule() {
        super("scoreboard", "Scoreboard", "Scoreboard overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        if (!game.inGame()) {
            return List.of();
        }
        return List.of("Scoreboard");
    }
}
