package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Server Address HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class ServerAddressModule extends HudModule {

    public ServerAddressModule() {
        super("server_address", "Server Address", "Server Address overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        return List.of(game.serverAddress());
    }
}
