package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Time HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class TimeModule extends HudModule {

    public TimeModule() {
        super("time", "Time", "Time overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        return List.of(new java.text.SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
    }
}
