package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * Totem Counter HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class TotemCounterModule extends HudModule {

    public TotemCounterModule() {
        super("totem_counter", "Totem Counter", "Totem Counter overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        if (!game.inGame()) {
            return List.of();
        }
        return List.of("Totem Counter");
    }
}
