package com.spaceline.client.module.hud;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import java.util.List;

import com.spaceline.client.engine.GameState;
import com.spaceline.client.hud.HudModule;

/**
 * TPS HUD element. Live values are supplied by the Fabric layer through
 * {@link GameState}; this declaration owns the id, category and settings.
 */
public final class TpsModule extends HudModule {

    public TpsModule() {
        super("tps", "TPS", "TPS overlay");    }

    @Override
    protected List<String> lines(GameState game) {
        return List.of(String.format("TPS: %.1f", game.tps()));
    }
}
