package com.spaceline.client.module.social;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;
import com.spaceline.common.module.setting.StringSetting;

/**
 * Nick Hider. A toggleable social feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class NickHiderModule extends ToggleModule {

    public NickHiderModule() {
        super("nick_hider", "Nick Hider", ModuleCategory.SOCIAL, "Nick Hider");
        register(new StringSetting("alias", "Alias", "Name to display instead", "You"));
    }
}
