package com.spaceline.client.module.social;
// Generated by generate_modules.py — part of the Space~line client module catalogue.

import com.spaceline.client.module.ToggleModule;
import com.spaceline.common.module.ModuleCategory;

/**
 * Voice. A toggleable social feature; the Fabric layer applies the in-game
 * effect based on this module's enabled state and settings.
 */
public final class VoiceModule extends ToggleModule {

    public VoiceModule() {
        super("voice", "Voice", ModuleCategory.SOCIAL, "Voice");    }
}
